name: Slack Lighthouse scores

on:
  call_workflow:
    secrets:
      LIGHTHOUSE_CHECK_WEBHOOK_URL:
        required: true
    inputs:
      urls:
        required: true

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: ${{ inputs.urls }}
        slackWebhookUrl: ${{ secrets.LIGHTHOUSE_CHECK_WEBHOOK_URL }}